### ISSUE TITLE
Replace build in build with Github Action

### ISSUE THREAD

**Issue by wp99cp** [cevi/Cevi-Tools-Webpage#7]
It seems the default build is buggy, we need to replace the default build mechanism with a GitHub Action script. Because the default build will add the title of the start page (index.html) to the header nav.

*Deployed Version:*
![Screenshot from 2021-12-09 22-45-13](https://user-images.githubusercontent.com/34008738/145480657-d357638a-3ac9-42ec-8378-db9eb1f8d372.png)

- [ ] Duplicate h1
- [ ] Unwanted link in header nav

*Preview Build:*
![Screenshot from 2021-12-09 22-47-21](https://user-images.githubusercontent.com/34008738/145480943-00a4f556-c911-47e3-8016-d60717e68ff0.png)

**Comment by maede97** [comment]
We might have to rename the current gh-pages branch to "main", and serve the built page from the gh-pages branch?

**Comment by wp99cp** [comment]
Strangely in the current version the title looks fine: https://cevi.tools/

**Comment by maede97** [comment]
Maybe @ThomasHaefliger changed some titles?

**Comment by maede97** [comment]
Otherwise, if the issue still persists, we could proceed as follows:
- [x] Rename gh-pages to main (branch out, set new main in settings?)
- [x] Add CI script to use jerryjvl/jekyll-build-action again, but instead of deploying to anywhere, simply copy the _site folder to gh-pages branch and serve the homepage statically from there using peaceiris/actions-gh-pages
